name: win_music
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.20.2
  fpdart: ^1.1.0
  # functional_widget: ^0.10.1
  # functional_widget_annotation: ^0.10.0
  hooks_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  sized_context: ^1.0.0+4
  youtube_explode_dart: ^2.0.2

  functional_widget:
    git:
      url: https://github.com/rrousselGit/functional_widget.git
      ref: master
      path: packages/functional_widget
  loading_animation_widget: ^1.2.0+4
  audioplayers: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^3.0.0-dev.3
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.3.0

flutter:
  uses-material-design: true
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-Light.ttf
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
        - asset: assets/fonts/TitilliumWeb-Italic.ttf
          style: italic  
